### ISSUE TITLE
Support own server

### ISSUE THREAD

**Issue by smehrbrodt** [solidtime-io/solidtime-desktop#2]
Currently the desktop app can only be used with the solidtime.io server.
Would be useful to configure it to use an own server.

**Comment by Onatcer** [comment]
This will be supported with the next release of the web application. The desktop client actually already supports this and you can configure the server when you first start the app or after logout. But we do not provide instructions on how to set up the OAuth Client yet, as there are API Endpoints missing in the latest web application community version release that are necessary to use the desktop client.

**Comment by Onatcer** [comment]
We added the instructions for self-hosting in the docs here: https://docs.solidtime.io/self-hosting/guides/docker#8-activate-desktop-client-access-optional

**Please make sure that you have at least version 0.2.0 of the solidtime server running, otherwise the desktop client will not work properly**
